apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: monitoring
  labels:
    app: go-app
    component: api
spec:
  selector:
    app: go-app
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
  type: ClusterIP # Internal service only
  sessionAffinity: None
